"""empty message

Revision ID: 2dd3d4516854
Revises: 4d3acce6c96e
Create Date: 2021-06-17 12:05:10.034400

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2dd3d4516854'
down_revision = '4d3acce6c96e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('product', 'image2',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('product', 'image3',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('product', 'image4',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('product', 'image4',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('product', 'image3',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('product', 'image2',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    # ### end Alembic commands ###
