"""empty message

Revision ID: 7f13920fd7ee
Revises: 2dd3d4516854
Create Date: 2021-06-17 16:23:16.746438

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7f13920fd7ee'
down_revision = '2dd3d4516854'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('slug', sa.String(length=140), nullable=True))
    op.create_unique_constraint(None, 'product', ['slug'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'product', type_='unique')
    op.drop_column('product', 'slug')
    # ### end Alembic commands ###
