"""empty message

Revision ID: 8f1d3d43be5a
Revises: 004aab3f809b
Create Date: 2021-06-10 15:27:12.453008

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8f1d3d43be5a'
down_revision = '004aab3f809b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order', 'status')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('status', sa.VARCHAR(length=10), nullable=True))
    # ### end Alembic commands ###
