"""empty message

Revision ID: d99229a2d816
Revises: f085a44d4bd0
Create Date: 2021-06-21 10:55:43.467623

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd99229a2d816'
down_revision = 'f085a44d4bd0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('title', sa.String(length=50), nullable=True))
    op.add_column('product', sa.Column('keyw', sa.String(length=150), nullable=True))
    op.add_column('product', sa.Column('desc', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product', 'desc')
    op.drop_column('product', 'keyw')
    op.drop_column('product', 'title')
    # ### end Alembic commands ###
