"""empty message

Revision ID: f085a44d4bd0
Revises: 7f13920fd7ee
Create Date: 2021-06-20 11:35:04.359691

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f085a44d4bd0'
down_revision = '7f13920fd7ee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('upload',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('file', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_column('product', 'slug')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('slug', sa.VARCHAR(length=140), nullable=True))
    op.drop_table('upload')
    # ### end Alembic commands ###
